when:
  - event: tag
    ref: refs/tags/v*

steps:
  build-and-test:
    image: suilteam/cxy:latest-ubuntu
    environment:
      DEBIAN_FRONTEND: noninteractive
    commands:
      - apt-get update
      - apt-get install -y --fix-missing ruby pkg-config libsystemd-dev libcap-dev
      - rake build
      - rake test

  release_docker_image:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKERHUB_USERNAME:
        from_secret: DOCKERHUB_USERNAME
      DOCKERHUB_TOKEN:
        from_secret: DOCKERHUB_TOKEN
    commands:
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
      - >
        docker build --build-arg RELEASE_TAG=${CI_COMMIT_TAG} . -t suilteam/cxy-playground-server:latest -t suilteam/cxy-playground-server:${CI_COMMIT_TAG}
      - >
        docker push suilteam/cxy-playground-server:latest
      - >
        docker push suilteam/cxy-playground-server:${CI_COMMIT_TAG}
